/*  File generated by: Map Ed v0.98.5 */

#include "../data/BG_Tiles.c"
#include "../data/BG_Maps.c"
#include "../data/BG_Palette.c"

extern const u16 bgPalette[256];
extern const u16 bgTiles[512];
extern const u16 bgMap[2048];
extern const u16 bgMap[2048];
